import React, { useState } from 'react';
import { X, Sparkles, Loader2, Lightbulb } from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  lang: 'fa' | 'en';
  currentPuzzle: any;
  chapterTitle: string;
}

export const AIHintModal: React.FC<Props> = ({
  isOpen,
  onClose,
  lang,
  currentPuzzle,
  chapterTitle,
}) => {
  const [hint, setHint] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  if (!isOpen) return null;

  const p1RoleText = currentPuzzle?.roseRoleText || currentPuzzle?.aetherRoleText;
  const p2RoleText = currentPuzzle?.aryaRoleText || currentPuzzle?.chronoRoleText;

  const fetchAIHint = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/hint', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chapterTitle,
          puzzleDescription: lang === 'fa' ? currentPuzzle?.description?.fa : currentPuzzle?.description?.en,
          p1Ability: p1RoleText ? (lang === 'fa' ? p1RoleText.fa : p1RoleText.en) : '',
          p2Ability: p2RoleText ? (lang === 'fa' ? p2RoleText.fa : p2RoleText.en) : '',
          lang
        })
      });

      const data = await res.json();
      setHint(data.hint || (lang === 'fa' ? 'کتاب جادویی دلدار: همزمانی و همفکری کلید موفقیت شماست!' : 'Magical Love Book: Synchronization and love is your key!'));
    } catch (e) {
      console.error('Hint error:', e);
      setHint(
        currentPuzzle?.hintDescription
          ? (lang === 'fa' ? currentPuzzle.hintDescription.fa : currentPuzzle.hintDescription.en)
          : (lang === 'fa' ? 'هماهنگی و ایثار کلید گشودن معماست!' : 'Cooperation is the key!')
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4 animate-fadeIn">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-lg w-full p-6 text-slate-100 shadow-2xl relative">
        
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 text-slate-400 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-lg transition-all"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-3 mb-6">
          <div className="p-3 bg-rose-500/20 border border-rose-500/30 rounded-xl text-rose-400">
            <Sparkles className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">
              {lang === 'fa' ? 'کتاب جادویی دلدار (راهنمای هوش مصنوعی)' : 'Magical Love Book (AI Hint)'}
            </h2>
            <p className="text-xs text-slate-400">
              {lang === 'fa' ? 'راهنمایی‌های رمانتیک و هوشمند کتاب جادویی برای عبور از معما' : 'Contextual story hints generated by Gemini AI'}
            </p>
          </div>
        </div>

        <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 mb-6">
          <h3 className="text-xs font-bold text-rose-400 mb-1">
            {currentPuzzle?.title ? (lang === 'fa' ? currentPuzzle.title.fa : currentPuzzle.title.en) : ''}
          </h3>
          <p className="text-xs text-slate-300">
            {currentPuzzle?.description ? (lang === 'fa' ? currentPuzzle.description.fa : currentPuzzle.description.en) : ''}
          </p>
        </div>

        {/* Display hint response */}
        {hint ? (
          <div className="bg-gradient-to-r from-rose-500/10 via-amber-500/10 to-rose-500/10 border border-rose-500/30 p-4 rounded-xl mb-6 relative">
            <div className="flex items-start gap-3">
              <Lightbulb className="w-5 h-5 text-rose-400 shrink-0 mt-0.5" />
              <p className="text-xs text-rose-200 leading-relaxed font-medium" dir={lang === 'fa' ? 'rtl' : 'ltr'}>
                {hint}
              </p>
            </div>
          </div>
        ) : (
          <div className="text-center py-4">
            <p className="text-xs text-slate-400 mb-4">
              {lang === 'fa' 
                ? 'کتاب جادویی وضعیت معما و توانایی‌های رز و آریا را تحلیل خواهد کرد...' 
                : 'The Love Book will analyze the current stage and abilities...'}
            </p>
          </div>
        )}

        <div className="flex items-center justify-end gap-2">
          <button
            onClick={fetchAIHint}
            disabled={loading}
            className="w-full py-2.5 bg-gradient-to-r from-rose-500 to-amber-600 hover:from-rose-400 hover:to-amber-500 text-slate-950 font-bold rounded-xl text-xs flex items-center justify-center gap-2 shadow-lg shadow-rose-500/20 transition-all disabled:opacity-50"
          >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            <span>
              {loading 
                ? (lang === 'fa' ? 'در حال دریافت راهنمایی از هوش مصنوعی...' : 'Consulting Love Book...') 
                : (hint ? (lang === 'fa' ? 'دریافت راهنمایی جدید' : 'Ask Again') : (lang === 'fa' ? 'دریافت راهنمایی هوشمند' : 'Get AI Hint'))}
            </span>
          </button>
        </div>

      </div>
    </div>
  );
};
